kind: pipeline
name: default

steps:
  - name: Build
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo:
        from_secret: dockerhub_repo
      tags: latest
    when:
      branch:
        - main
  - name: notify
    image: clortox/drone-ntfy
    settings:
      URL: https://ntfy.clortox.com
      USERNAME: drone
      PASSWORD:
        from_secret: ntfy_password
      TOPIC: drone-builds
      MESSAGE: Drone-ntfy has finished building!
      CLICK: https://drone.clortox.com/tyler/drone-ntfy
      TITLE: Drone (drone-ntfy)
    when:
      branch:
        - main
